name: Update GitHub Pages Metrics

on:
  schedule:
    - cron: '0 0 * * 1' # Weekly schedule
  workflow_dispatch: # Manual trigger

permissions:
  contents: write
  statuses: write

jobs:
  update-metrics:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Cache apt packages to speed up installation
      - name: Cache apt packages
        uses: actions/cache@v4
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-cache
          restore-keys: ${{ runner.os }}-apt-cache

      # Step 3: Install jq for JSON processing
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      # Step 4: Fetch and generate metrics.json
      - name: Generate metrics.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Define variables
          ORG_NAME="stacksmiths"
          API_URL="https://api.github.com/orgs/$ORG_NAME/repos"
          METRICS_FILE="data/metrics.json"
          
          # Clean and prepare directories
          rm -rf data && mkdir -p data

          # Fetch repositories data
          response=$(curl -s -w "%{http_code}" -o repos.json -H "Authorization: token $GITHUB_TOKEN" "$API_URL")
          status_code=$(tail -c 3 <<< "$response")
          if [ "$status_code" -ne 200 ]; then
              echo "Failed to fetch repository data. HTTP Status: $status_code"
              exit 1
          fi
          response=$(head -c -3 <<< "$response")

          # Parse, sort, and generate metrics.json
          echo "$response" | jq 'map({name: .name, stars: .stargazers_count}) | sort_by(-.stars) | .[:5] | from_entries' > "$METRICS_FILE"
          echo "metrics.json generated successfully."

      # Step 5: Commit and push changes
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update metrics.json with top repositories on $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          add: "data/metrics.json"
